### ISSUE TITLE
Close all tabs from this domain

### ISSUE THREAD

**Issue by smaragdus** [hacktoolkit/organize-tabs-chrome-extension#2]
**Suggestion**

I have a suggestion for adding a new command in the extension pop-up:

- `Close all tabs from this domain`

**Behaviour**

When the user opens extension pop-up and executes `Close all tabs from this domain` command, [Organize Tabs](https://github.com/hacktoolkit/organize-tabs-chrome-extension) will close all tabs from the domain of the active tab.

**Example**

There are 15 tabs open. 5 of these tabs are from GitHub domain. When GitHub tab is active and the user executes `Close all tabs from this domain` command, all GitHub tabs will be closed.

**Usability**

This new command will offer a quick way to purge all tabs belonging to a certain domain.

**Comment by jontsai** [comment]
There is currently the ability to Collate tabs by domain, and then all of the tabs will be grouped by domain into separate windows. Then, you can just rapidly close all of those tabs, or the entire window. This allows one to double-check before just closing.

But, I also see the value in closing all the tabs from a domain (in cases where you know you don't need it at all, anymore, without double-checking)

**Comment by smaragdus** [comment]
@jontsai 

> But, I also see the value in closing all the tabs from a domain (in cases where you know you don't need it at all, anymore, without double-checking)

This was exactly my point. For achieving this I am currently using another extension- **OhMyTab** ([Chrome Web Store](https://chrome.google.com/webstore/detail/ohmytab/hkeiholeokdmhlfjblopimaieeikpnek), [GitHub](https://github.com/hrontan/OhMyTab)), but if this feature is implemented in [Organize Tabs](https://github.com/hacktoolkit/organize-tabs-chrome-extension) I will not need it any more.

**Comment by jontsai** [comment]
@smaragdus Thank you again for submitting this issue. A new version has been submitted to the Chrome webstore. It will be v0.4.0 when it is approved.

https://chrome.google.com/webstore/detail/organize-tabs/ebnlpacdgjnofakgfgbildmjdhbibnpa

**Comment by smaragdus** [comment]
@jontsai 

Thank you very much! I hope that the new version (0.4.0) will be approved soon. When the new version of [Organize Tabs](https://github.com/hacktoolkit/organize-tabs-chrome-extension) appears on [Chrome Web Store](https://chrome.google.com/webstore/detail/organize-tabs/ebnlpacdgjnofakgfgbildmjdhbibnpa) I will test it.  By the way your extension has become one of my favourites, a really indispensable one.

Thank you for maintaining and improving this excellent extension!

**Comment by jontsai** [comment]
@smaragdus hey there, it looks like 0.4.0 is live now!

Here is the link to download again:
https://chrome.google.com/webstore/detail/organize-tabs/ebnlpacdgjnofakgfgbildmjdhbibnpa

(btw, I had to remove, then re-install... not sure if there is a way to "update" directly)

**Comment by smaragdus** [comment]
@jontsai 

I have just tested [Organize Tabs](https://hacktoolkit.github.io/organize-tabs-chrome-extension/)  [version](https://github.com/hacktoolkit/organize-tabs-chrome-extension/releases)  [0.4.0](https://github.com/hacktoolkit/organize-tabs-chrome-extension/releases/tag/v0.4.0) and I can confirm that **Close All Tabs from this Domain** command works as expected, flawless implementation. Now I can use your extension to replace 3 other extensions, excellent work, thanks!
