### ISSUE TITLE
Context Menu Integration

### ISSUE THREAD

**Issue by smaragdus** [hacktoolkit/organize-tabs-chrome-extension#3]
Currently [Organize Tabs](https://github.com/hacktoolkit/organize-tabs-chrome-extension) commands can be executed from extension's pop-up. I suppose a further enhancement may be context menu integration so that the user may execute these commands from context menu- Organize Tabs context menu item with sub-menu items for all available commands, example:

- Organize Tabs
  - Collate Tabs
  - Consolidate Tabs
  - Deduplicate Tabs
  - Sort Tabs in Window
  - Close Blank Tabs

If context menu integration is implemented, in extension options may be added a check-box to enable/disable context menu integration.

**Comment by jontsai** [comment]
Thank you for this great feature suggestion @smaragdus, will look into implementing this, next!

**Comment by smaragdus** [comment]
@jontsai 

It is always great when a great piece of software gets even better, and this is the case with your extension. I am very glad that you continue to maintain and improve your [Organize Tabs](https://hacktoolkit.github.io/organize-tabs-chrome-extension/) extension. I hope that more people will discover and appreciate your extremely useful extension. Thank you very much for your work!

God bless!

**Comment by jontsai** [comment]
Thanks again @smaragdus for the great feature suggestion.

This is now resolved by #8 

Version 0.8.0 has been submitted for release to the Chrome Web Store, and will become available once it is approved by the Chrome Web Store reviewers: https://chrome.google.com/webstore/detail/organize-tabs/ebnlpacdgjnofakgfgbildmjdhbibnpa
